appname = "Uranus"
port = 2952
address = "0.0.0.0"
dbus_port = 55556
mission_retry_number = 3
async_process = true
database_driver = "sqlite"

[mysql]
ip = "192.168.56.19"
port = 3310
user = "root"
password = 123456
database = "cmp"
max_open_connection = 100
max_idle_connection = 100

[sqlite]
file = "/uranus/uranus"
database = "uranus"
max_open_connection = 100
max_idle_connection = 100